[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
jotdown = "0.4.0"
markdown = "1.0.0-alpha.17"
regex = "1.10.4"
tokio = "1.37.0"
